@startuml BuyRecruitUseCase
participant InnController
participant BuyRecruitUseCase
participant PartyService
participant Inn

activate InnController
InnController -> BuyRecruitUseCase: buyRecruit(name: String)
activate BuyRecruitUseCase

par
BuyRecruitUseCase -> Inn: buyRecruit(name: String)
activate Inn
Inn -> Inn: hasRecruit(name: String)
Inn -> Inn: canAffordRecruit(Hero: Hero)
Inn -> BuyRecruitUseCase: hero: Hero / throws Exception

else
BuyRecruitUseCase -> PartyService: addHero(hero: Hero)
activate PartyService
PartyService -> PartyService: hasSpace()
end

alt any failures 
par
    note right of BuyRecruitUseCase: undo commands that ran

BuyRecruitUseCase -> Inn: sellHero(hero: Hero) (if bought)
Inn -> Inn: addGold(hero.value())
deactivate Inn

else 
BuyRecruitUseCase -> PartyService: removeHero() (if added)
deactivate PartyService

end 
end
BuyRecruitUseCase -> InnController: Result: DTO
deactivate BuyRecruitUseCase


ref over InnController: interact-with-inn.puml

@enduml