@startuml name 
participant InnController
participant BuyItemUseCase
participant InventoryService
participant Inn

activate InnController
InnController -> BuyItemUseCase: buyx(amount: int)
activate BuyItemUseCase 
BuyItemUseCase -> Inn: buyx(amount: int)
note left of Inn
buyx Default = 1
end note
activate Inn

alt Have enough gold
Inn -> BuyItemUseCase: amount: int
' add to InventoryService
BuyItemUseCase -> InventoryService: addx(amount = int)
activate InventoryService
InventoryService -> BuyItemUseCase: sucess: booleam
deactivate InventoryService
else Not enough Gold
Inn -> BuyItemUseCase: Throws Exception
deactivate Inn
end

BuyItemUseCase -> InnController: Result: DTO
deactivate BuyItemUseCase

ref over InnController: interact-with-inn.puml


@enduml