@startuml name 
participant InnController
participant BuyItemUseCase
participant InventoryService

activate InnController
InnController -> BuyItemUseCase: placeOrder(id: int, amount: int)
activate BuyItemUseCase 
BuyItemUseCase -> InventoryService: buyItem(id: int, amount: int)
note left of InventoryService
buyx Default = 1
end note
activate InventoryService

alt Have enough gold
InventoryService -> BuyItemUseCase: amount: int
' add to InventoryService

else Not enough Gold
InventoryService -> BuyItemUseCase: Throws Exception
deactivate InventoryService
end

BuyItemUseCase -> InnController: Result: DTO
deactivate BuyItemUseCase

ref over InnController: interact-with-inn.puml


@enduml