@startuml interact with Inn

participant RoomChance

' Inn is concrete that the user 
participant PartyService
participant Inn
participant BuyRecruitUseCase
participant ViewRecruitUseCase
participant BuyItemUseCase
participant getShopUseCase
participant InnController
actor User


' RoomChance selects Inn
activate RoomChance
RoomChance -> Inn: nextRoom()
deactivate RoomChance
activate Inn

Inn -> PartyService: maxRestore()
activate PartyService


PartyService -> Inn: status: String
deactivate PartyService
Inn -> InnController: status: String 
deactivate Inn
activate InnController


InnController -> User: status: GUI
deactivate InnController
' User given option to pick one of many different commands

alt
' User wants to View Shop
User -> InnController: view menu
activate InnController

InnController -> getShopUseCase
activate getShopUseCase
ref over getShopUseCase:"getShop.puml"
getShopUseCase -> InnController: shop: DTO
deactivate getShopUseCase
InnController -> User: shop: GUI
deactivate InnController

else
' User attempts to buy item
User -> InnController: buy item x times
activate InnController
' Checks if they have enough gold
InnController -> BuyItemUseCase: placeOrder(itemId: int, amount: int)
activate BuyItemUseCase
ref over BuyItemUseCase: "Buyitem.puml"
BuyItemUseCase -> InnController: Result: DTO
deactivate BuyItemUseCase 
InnController -> User: Sucess/fail: GUI
deactivate InnController


else

' view recuitment
User -> InnController: view recruit menu
activate InnController
InnController -> ViewRecruitUseCase: viewRecruit()
activate ViewRecruitUseCase
ref over ViewRecruitUseCase: "ViewRecruit.puml"
ViewRecruitUseCase -> InnController: Recruits: DTO
deactivate ViewRecruitUseCase
InnController -> User: Recruit List: GUI
deactivate InnController

else
' User attempts to recruit
User -> InnController: buy recruit x
activate InnController
InnController -> BuyRecruitUseCase
activate BuyRecruitUseCase
ref over BuyRecruitUseCase: "BuyRecruit.puml"
' First, Attempts to buy Recruit
BuyRecruitUseCase -> InnController: Result: DTO
deactivate BuyRecruitUseCase
InnController -> User: sucess/fail popup: GUI
deactivate InnController


'Go to Next Room
User -> InnController: nextRoom()
activate InnController
InnController -> RoomChance: nextRoom()
deactivate InnController
activate RoomChance

ref over RoomChance:"go through a single battle"
    note left 
        Details in [FILE NAME]
    end note 
deactivate RoomChance
end
@enduml
