# Database Configuration
database.url=jdbc:mysql://localhost:3306/rpg_game
database.user=root
database.password=password

# Spring Boot Configuration
spring.application.name=campaign-persistence
spring.main.banner-mode=off
