package com.github.campaign_progression.application;

import java.util.Optional;

import com.github.campaign_progression.application.dto.BuyRecruitResponseDTO;
import com.github.campaign_progression.domain.HeroState;
import com.github.campaign_progression.domain.Inn;
import com.github.campaign_progression.domain.InventoryService;
import com.github.campaign_progression.domain.PartyService;

/**
 * Use case responsible for recruiting heroes from an inn.
 *
 * <p>This class coordinates between the {@link Inn}, {@link PartyService},
 * and {@link InventoryService} to validate recruitment conditions and
 * perform the recruitment.</p>
 *
 * <p>Rules:
 * <ul>
 *     <li>Recruits are only available in the first 10 rooms</li>
 *     <li>Party must have available space</li>
 *     <li>Recruit must be generated by the inn</li>
 *     <li>Player must have enough gold (unless level 1 hero)</li>
 * </ul>
 * </p>
 */
public class BuyRecruitUseCase {

    private final Inn inn;
    private final PartyService partyService;
    private final InventoryService inventoryService;

    /**
     * Constructs the use case with required dependencies.
     *
     * @param inn the inn responsible for generating recruits
     * @param partyService the party manager
     * @param inventoryService the player's inventory/gold manager
     */
    public BuyRecruitUseCase(Inn inn, PartyService partyService, InventoryService inventoryService) {
        this.inn = inn;
        this.partyService = partyService;
        this.inventoryService = inventoryService;
    }

    /**
     * Attempts to recruit a hero based on the current room.
     *
     * @param roomCounter the current room number
     * @return a {@link BuyRecruitResponseDTO} describing the result
     */
    public BuyRecruitResponseDTO execute(int roomCounter) {

        if (roomCounter > 10) {
            return new BuyRecruitResponseDTO(
                    false,
                    "Recruits are no longer available after room 10",
                    null, null, 0
            );
        }

        if (!partyService.hasSpace()) {
            return new BuyRecruitResponseDTO(
                    false,
                    "Party is full. Cannot recruit more heroes.",
                    null, null, 0
            );
        }

        Optional<HeroState> recruitOpt = inn.generateRecruit(partyService, roomCounter);

        if (recruitOpt.isEmpty()) {
            return new BuyRecruitResponseDTO(
                    false,
                    "No recruit available",
                    null, null, 0
            );
        }

        HeroState hero = recruitOpt.get();

        int level = hero.getLevel();
        int cost = (level == 1) ? 0 : level * 200;

        if (!inventoryService.canAfford(cost)) {
            return new BuyRecruitResponseDTO(
                    false,
                    "Not enough gold to recruit hero. Cost: " + cost,
                    null, null, 0
            );
        }

        try {
            if (cost > 0) {
                inventoryService.minusGold(cost);
            }

            partyService.addHero(hero);

            return new BuyRecruitResponseDTO(
                    true,
                    "Recruit successful (Cost: " + cost + ")",
                    hero.getName(),
                    hero.getSpecialization(),
                    level
            );

        } catch (IllegalStateException ex) {
            return new BuyRecruitResponseDTO(
                    false,
                    ex.getMessage(),
                    null, null, 0
            );
        }
    }
}