@startuml

component [Profile] {
  [PVE Data]
  [PVP Data]
  component Ranking
  component Party
  component CampaignProgress
  component Scores

}

[User]
[DataBase]

component [Login]{
    portin Username
    portin Password
    portin Email
}



component [ProfileManager]

component C {
  portin profile1
  portin profile2
  portin profile3
  portin profile4
  component game
}

User --> Username
User --> Password
User --> Email
DataBase --> Username
DataBase --> Password
DataBase --> Email


Login --> ProfileManager

profile1 ..> Profile : loads
profile2 ..> Profile : loads
profile3 ..> Profile : loads
profile4 ..> Profile : loads


profile1 --> game
profile2 --> game
profile3 --> game
profile4 --> game

ProfileManager --> profile1
@enduml