' User wants to View Shop
@startuml ViewRecruitUseCase
participant InnController
participant ViewRecruitUseCase
participant Inn

activate InnController
InnController -> ViewRecruitUseCase: getShop()
activate ViewRecruitUseCase
ViewRecruitUseCase -> Inn: getShop()
activate Inn
Inn -> ViewRecruitUseCase: shop: String
deactivate Inn
ViewRecruitUseCase -> InnController: shop: DTO
ref over InnController: interact-with-inn.puml

deactivate ViewRecruitUseCase
@enduml