@startuml
'add abstract class enetity' 
class Hero {
    - name: String
    - class: String   
    - mageSPL: int[mana = 5, attack = 1]
    - warriorSPL: int[attack = 2, defense = 3]
    - orderSPL: int[mana = 5, defense = 2]
    - chaosSPL: int[attack = 3, health = 5]
    'Uniervsal Stats per level gives points before the class bonus is applied per level up'
    - UniversalSPL: int[attack = 1, defense = 1, health = 5, mana = 2]
    - health: int = 100
    - Mana: int = 50
    - level: int = 1
    - gold: int = 0
    - experience: int = 0
    - defnese: int = 5
    - attack: int = 5
    - Exp(L) = Exp(L-1)+500+75*L+20*L2
    'Add class Abstract class with all classes'
    - health: int
    - Mana: int
    - level: int
    'add -levels for each class'
    - gold: int
    - experience: int
    'add to check if enough experience to level up'
    - experienceThreshold: int
    - defnese: int
    - attack: int
    '-spells: List[Spells]'
    + GetHealth(): int
    + SetHealth(health: int): void
    + GetMana(): int
    + SetMana(mana: int): void
    + Getlevel(): int
    + SetlevelUp(level: int): void
    + SetlevelUp(amount: int): void 
    'Change to levelUp():void' that increases level by 1'
    + levelUp(attackstats, defensestats, healthstats, manastats): void
    + GetGold(): int
    + SetGold(gold: int): void 
    + GetExperience(): int
    + SetExperience(exp: int): void
    + GetDefense(): int
    + SetDefense(damage: int): void
    + Getattack(): int
    + Setattack(attack: int): void
    + ClassType(Class: String): void
    + Setattack(amount: int): void
}


class Enemy {
    '1 to 5 enemies'
    'level from 1 to 10'
    'the actual level of the enemy party is determined by the culmative level of the hero party'
    'if hero party has a culmative level of 5 the enemy party will have a culmative level of 5-0'
    'The maximum level of a full enemy party culmative level is 50'
    - name: String
    - health: int = 100
    - Mana: int = 50
    - level: int = 1
    - defnese: int = 5
    - attack: int = 5
    + GetHealth(): int
    + SetHealth(health: int): void
    + GetMana(): int
    + SetMana(mana: int): void
    + Getlevel(): int
    + GetDefense(): int
    + SetDefense(damage: int): void
    + Getattack(): int
    + Setattack(attack: int): void
    'G(L) = 75*L that is the gold given to hero on defeat'
    + GiveGold(level: int): int level * 75
    'Exp(L)=50*L that is the experience given to hero on defeat'
    + GiveExperience(level: int): int level * 50
}


'Order' <|-- Hero : +5 Mana
'Order' <|-- Hero : +2 Defense
'Order' <|-- Hero : Heals/Shields
'Chaos' <|-- Hero : +3 Attack
'Chaos' <|-- Hero : +5 HP
'Chaos' <|-- Hero : Fireball/Lightning
'Warrior' <|-- Hero : +2 Attack
'Warrior' <|-- Hero : +3 Defense
'Warrior' <|-- Hero : Cleave/PHYSICAL
'Mage' <|-- Hero : +5 Mana
'Mage' <|-- Hero : +1 Attack
'Mage' <|-- Hero : Mana Replenish
@enduml