@startuml

participant RoomChance

' Inn is concrete that the user 
participant PartyService
participant BuyRecruitUseCase
participant ViewRecruitUseCase
participant BuyItemUseCase
participant getShopUseCase
participant InnController
actor User


' RoomChance selects Inn
activate RoomChance
RoomChance -> Inn: nextRoom()
deactivate RoomChance
activate Inn

Inn -> PartyService: maxRestore()
activate PartyService


PartyService -> Inn: status: String
deactivate PartyService
Inn -> InnController: status: String 
deactivate Inn
activate InnController


InnController -> User: status: String
deactivate InnController
' User given option to pick one of many different commands

alt
' User wants to View Shop
User -> InnController: getShop()
activate InnController

InnController -> getShopUseCase
activate getShopUseCase
ref over getShopUseCase:"buyx.puml"
getShopUseCase -> InnController: ????
deactivate getShopUseCase
InnController -> User: shop: String
deactivate InnController

else
' User attempts to buy item
User -> InnController: buyx(amount: int)
activate InnController
' Checks if they have enough gold
InnController -> BuyItemUseCase
activate BuyItemUseCase
ref over BuyItemUseCase: "Buyitem.puml"
BuyItemUseCase -> InnController: ????
deactivate BuyItemUseCase 

else

' view recuitment
User -> InnController: viewRecruit()
activate InnController
InnController -> ViewRecruitUseCase: 
activate ViewRecruitUseCase
ref over ViewRecruitUseCase: "ViewRecruit.puml"
ViewRecruitUseCase -> InnController: ????
deactivate ViewRecruitUseCase
InnController -> User: Recruits: String
deactivate InnController
InnController -> User: ???
deactivate InnController

else
' User attempts to recruit
User -> InnController: buyRecruit(name: String)
activate InnController
InnController -> BuyRecruitUseCase
activate BuyRecruitUseCase
ref over BuyRecruitUseCase: "BuyRecruit.puml"
' First, Attempts to buy Recruit
BuyRecruitUseCase -> InnController: ???
deactivate BuyRecruitUseCase


'Go to Next Room
User -> InnController: nextRoom()
activate InnController
InnController -> RoomChance: nextRoom()
deactivate InnController
activate RoomChance

ref over RoomChance:"go through a single battle"
    note left 
        Details in [FILE NAME]
    end note 
deactivate RoomChance
end
@enduml
