'1.	As a user I should be able to create a profile and log in.
'At a minimum, the profile should consist of a username and password for authentication. 
'The main purpose of the profile is to connect persistently stored data, such as parties, scores, rankings, campaign progress, 
'to an existing account. Once I am authenticated and logged in, I should be directed to a GUI,
'where I can review my saved data, and pick a game mode (e.g., PvE or PvP).

@startuml
actor User
participant Database
participant ProfileManager
participant Profile
participant GUI

User -> ProfileManager : Login(Username,Password)

DataBase -> ProfileManager : VerifyLogin(Username,Password)


alt [VerifyLogin(Username,Password) == true]
    'A if statement that if the 
    'User -> ProfileManager: Username
    'User -> ProfileManager: Password
    ProfileManager -> Profile :Choose Profile
    Profile -> GUI :Scores
    Profile -> GUI :Campaign progress
    Profile -> GUI :Party
    Profile -> GUI :Ranking
    Profile -> GUI :PVP
    Profile -> GUI :PVE
    'PvE or PvP"

else [VerifyLogin == ThreeAttempts]
 'Blocked user
 'Incorrect password locked out'
 ProfileManager -> User: Account Blocked 2 hours
 ProfileManager -> User: Ask to reset Password via email


end

@enduml 