@startuml
class Hero {
    - name: String
    - class: String   
    - mageSPL: int[mana = 5, attack = 1]
    - warriorSPL: int[attack = 2, defense = 3]
    - orderSPL: int[mana = 5, defense = 2]
    - chaosSPL: int[attack = 3, health = 5]
    - health: int = 100
    - Mana: int = 50
    - level: int = 1
    - gold: int = 0
    - experience: int = 0
    - defnese: int = 5
    - attack: int = 5
    - Exp(L) = Exp(L-1)+500+75*L+20*L2
    + GetHealth(): int
    + SetHealth(health: int): void
    + GetMana(): int
    + SetMana(mana: int): void
    + Getlevel(): int
    + SetlevelUp(level: int): void
    + GetGold(): int
    + SetGold(gold: int): void 
    + GetExperience(): int
    + SetExperience(exp: int): void
    + GetDefense(): int
    + SetDefense(damage: int): void
    + Getattack(): int
    + Setattack(attack: int): void
    + ClassType(Class: String): void
    
    
}

'Order' <|-- Hero : +5 Mana
'Order' <|-- Hero : +2 Defense
'Order' <|-- Hero : Heals/Shields
'Chaos' <|-- Hero : +3 Attack
'Chaos' <|-- Hero : +5 HP
'Chaos' <|-- Hero : Fireball/Lightning
'Warrior' <|-- Hero : +2 Attack
'Warrior' <|-- Hero : +3 Defense
'Warrior' <|-- Hero : Cleave/PHYSICAL
'Mage' <|-- Hero : +5 Mana
'Mage' <|-- Hero : +1 Attack
'Mage' <|-- Hero : Mana Replenish
@enduml