@startuml CampaignManager
skinparam Style strictuml
skinparam SequenceMessageAlignment center



abstract class CampaignManager{
    #_battleChance: float 
    #_roomCounter: int
    + getBattleChance(): float
    + setBattleChance(percent: float): void
    + getRoomCounter(): int
    + increaseRoomCounter(): void
    + nextRoom(): Room
} 

abstract class Room{

}

class Inn {
    - {static} SHOPLIST : List<Item>
    - Recruits: map<name: String, hero: Hero>

    + recover(): void
    + viewRecruits(): map<name: String, hero: Hero>
    + buyItem(id: int, amount: int): Item
    + buyRecruit(id: int, amount: int): Hero
    + sellHero(hero: Hero)
    + addGold(amount: int)
    - CanAffordRecruit(hero: Hero): boolean
    - hasRecruit(name: String): boolean
    + getShop(): List[Item]
}
class BattleRoom{
}
class Spawn{
}
class PartyService{
    - heros: List[Hero]
    + maxRestore(): String
    + addHero(hero: Hero)
    - hasSpace(): boolean
}
class InnView <<boundary>>{
    + showPartyHealed()
    + ShowShop()
    + SucessfulTransaction()
    + FailedTransaction()
    + RecruitList()
    + BoughtHero()
}
class battleEnd <<boundary>>{
    + onNextRoomClicked()
}
class InnController <<control>> {
    + getShop()
    + buyItem(id: int, amount: int = 1)
    + viewRecruit(name: String)
    + buyRecruit(name: String)
    + Intialize(): DTO
}
class BattleController <<control>> {
    + Intialize(): DTO
}
class RoomController <<control>>{
    + attmptNextRoom()
    + attemptIntialize()
}
class InnIntializeUseCase <<APPLICATION>>{
    + maxRestore(): String
}
class NextRoomUseCase <<APPLICATION>>{
    + NextRoom(): Room
}
class BuyRecruitUseCase <<APPLICATION>> {
    + buyRecruit(name: String): DTO

}
class ViewRecruitUseCase <<APPLICATION>>{
    + getRecuits(): DTO
}
class BuyItemUseCase <<APPLICATION>>{
    + buyItem(id: int, amount: int = 1)

}
class getShopUseCase <<APPLICATION>>{
    + getShop()
}

abstract class Item{
    # cost: int
    # hpHeal: int
    # manaHeal: int
    # canRevive = false: boolean
    + getCost(): int
    + getHpHeal(): int
    + getManaHeal(): int
    + getCanRevive(): boolean
}
class Bread{
    - cost = 200
    - hpHeal = 20
    - manaHeal = 0
}
class Cheese{
    - cost = 500
    - hpHeal = 50
    - manaHeal = 0
}
class Steak{
    - cost = 1000
    - hpHeal = 200
    - manaHeal = 0
}
class Water{
    - cost = 150
    - hpHeal = 0
    - manaHeal = 10   
}
class Juice{
    - cost = 450
    - hpHeal = 0
    - manaHeal = 30
}
class Wine{
    - cost = 750
    - hpHeal = 0
    - manaHeal = 100
}
class Elixir{
    - cost = 2000
    - hpHeal = 9999
    - manaHeal = 9999
    - canRevive = true    
}

Item <|-- Bread
Item <|-- Cheese
Item <|-- Steak
Item <|-- Water
Item <|-- Juice
Item <|-- Wine
Item <|-- Elixir

class InventoryService{
    - gold: int
    - items: List<Item>
    + addItem(Id: int, amount: int)
    + buyItem(Id: int, amount: int)

}
CampaignManager <-- Room 

CampaignManager <-- NextRoomUseCase
Room <|-- Inn
Room <|-- BattleRoom
Room <|-- Spawn

Inn <-- getShopUseCase
InventoryService <-- BuyItemUseCase
Inn <-- ViewRecruitUseCase
PartyService <-- InnIntializeUseCase

InnIntializeUseCase <-- InnController
BuyRecruitUseCase <-- InnController
ViewRecruitUseCase <-- InnController
BuyItemUseCase <-- InnController
getShopUseCase <-- InnController

NextRoomUseCase <- RoomController

InnController <-- InnView
RoomController <-- battleEnd


@enduml